version: 0.1
phases:
  install:
    commands:
      - "npm install -g yarn"
      - "yarn global add gatsby-cli"
      - "yarn global add purgecss"
      - apt-get update
      - apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
      - "yarn test:ci"
  build:
    commands:
      - "yarn build"
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://ryanparker.dev" --delete'
      - 'aws cloudfront create-invalidation --distribution-id E28J5S6RMWA0JH --paths "/*"'
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
cache:
  paths:
    - ".cache/*"
    - "public/*"