name: Lint-Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build